version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env/development/database
  web:
    build: .
    volumes:
      - .:/survey
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env/development/database
      - .env/development/web
